# Generated by Django 4.1.3 on 2024-08-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(default='', max_length=5, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('progress', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
